In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import mean_squared_error, precision_score
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [2]:
train_dataset = np.genfromtxt('resources/train.csv', dtype=np.float32, delimiter=',')
train_targets = train_dataset[:,-1]
test_dataset = np.genfromtxt('resources/test.csv', dtype=np.float32, delimiter=',')
test_targets = test_dataset[:,-1]
combined_dataset=np.concatenate((train_dataset[:,:-1], test_dataset[:,:-1]))

In [3]:
numeric_indices = []
for i in range(combined_dataset.shape[1]):
    n_unique = len(np.unique(combined_dataset[:, i]))
    numeric_indices.append(n_unique > 2)
print len(numeric_indices)
numeric_indices = np.array(numeric_indices, dtype=np.bool)        

122


In [4]:
combined_dataset[:, numeric_indices] = StandardScaler().fit_transform(
                                        combined_dataset[:, numeric_indices]
                                        )

In [5]:
batch_size = 1500
num_feature = 122
num_labels = 5
graph = tf.Graph()
with graph.as_default():

    tf_noisy_train_dataset = tf.placeholder(tf.float32, shape=(None, num_feature))
    tf_train_dataset = tf.placeholder(tf.float32, shape=(None, num_feature))
    tf_test_dataset = tf.constant(combined_dataset)
    
    n_hidden_1 = 50
#     n_hidden_2 = 100
#     n_hidden_3 = 500
    n_input = num_feature

    wh1 = tf.Variable(tf.truncated_normal([n_input, n_hidden_1], dtype=tf.float32))
#     wh2 = tf.Variable(tf.truncated_normal([n_hidden_1, n_hidden_2], dtype=tf.float32))
#     wh3 = tf.Variable(tf.truncated_normal([n_hidden_2, n_hidden_3], dtype=tf.float32))
#     wo = tf.Variable(tf.zeros([n_hidden_1, n_input], dtype=tf.float32))
#     wo.initialized_value = tf.transpose(wh1)
    b1 = tf.Variable(tf.truncated_normal([n_hidden_1], dtype=tf.float32))
#     b2 = tf.Variable(tf.truncated_normal([n_hidden_2], dtype=tf.float32))
#     b3 = tf.Variable(tf.truncated_normal([n_hidden_3], dtype=tf.float32))
    bo = tf.Variable(tf.truncated_normal([n_input], dtype=tf.float32))
    layer_1 = tf.add(tf.matmul(tf_train_dataset, wh1), b1)
    def compute_logit(x):
#         layer_2 = tf.nn.relu(tf.add(tf.matmul(layer_1, wh2), b2))
#         layer_3 = tf.nn.sigmoid(tf.add(tf.matmul(layer_2, wh3), b3))
        return tf.matmul(layer_1, tf.transpose(wh1)) + bo 

    
    logits = compute_logit(tf_noisy_train_dataset)
    difference = tf.sub(tf_train_dataset, logits) 
    loss = tf.sqrt(tf.reduce_mean(tf.square(difference)))# +  0.0001 * (tf.nn.l2_loss(wh1) + tf.nn.l2_loss(wo))
#     loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits,tf_train_dataset))
    optimizer = tf.train.AdamOptimizer(0.001).minimize(loss)
    train_prediction = compute_logit(tf_train_dataset)

In [6]:
num_steps = 10000
preds = []
randomized_dataset = combined_dataset.copy()
np.random.shuffle(randomized_dataset)
new_input=[]
with tf.Session(graph=graph) as session:
    tf.initialize_all_variables().run()
    print ("Initialized")
    for step in range(num_steps):
        offset = (step * batch_size) % (randomized_dataset.shape[0] - batch_size)

        batch_data = randomized_dataset[offset:(offset + batch_size), :]
        noisy_batch_data = batch_data.copy()
        for i, point in enumerate(noisy_batch_data):
            noisy_batch_data[i, :] = point + np.random.normal(0, 0.25, noisy_batch_data.shape[1])
        feed_dict = {tf_train_dataset : batch_data, tf_noisy_train_dataset: noisy_batch_data}
        _, l, predictions = session.run(
          [optimizer, loss, train_prediction], feed_dict=feed_dict)
        if (step % 500 == 0):
            print("Minibatch loss at step", step, ":", l)
#             print "SKLEARN loss", np.sqrt(mean_squared_error(predictions, batch_data))
    new_input=layer_1.eval(feed_dict = {tf_train_dataset :combined_dataset})

Initialized
('Minibatch loss at step', 0, ':', 36.835251)
('Minibatch loss at step', 500, ':', 11.012452)
('Minibatch loss at step', 1000, ':', 13.597469)
('Minibatch loss at step', 1500, ':', 3.3799033)
('Minibatch loss at step', 2000, ':', 2.3000276)
('Minibatch loss at step', 2500, ':', 1.2403545)
('Minibatch loss at step', 3000, ':', 0.80488724)
('Minibatch loss at step', 3500, ':', 0.53259474)
('Minibatch loss at step', 4000, ':', 0.40530542)
('Minibatch loss at step', 4500, ':', 1.5904599)
('Minibatch loss at step', 5000, ':', 0.22646885)
('Minibatch loss at step', 5500, ':', 0.16779025)
('Minibatch loss at step', 6000, ':', 0.12651327)
('Minibatch loss at step', 6500, ':', 0.12335484)
('Minibatch loss at step', 7000, ':', 0.088059731)
('Minibatch loss at step', 7500, ':', 0.11866655)
('Minibatch loss at step', 8000, ':', 0.071507461)
('Minibatch loss at step', 8500, ':', 0.068368487)
('Minibatch loss at step', 9000, ':', 0.061218556)
('Minibatch loss at step', 9500, ':', 0.05493

In [7]:
#saving new train & test data 
from collections import Counter
new_train_data=new_input[:train_dataset.shape[0]]
new_train_data=np.c_[new_train_data,train_targets]
new_test_data=new_input[train_dataset.shape[0]:]
new_test_data=np.c_[new_test_data, test_targets]
print(Counter(test_targets))
np.savez('out/new_input.npz',train=new_train_data, test=new_test_data)

Counter({2.0: 9711, 1.0: 7458, 4.0: 2554, 3.0: 2421, 5.0: 400})


In [8]:
model = LogisticRegression(C=1,class_weight='balanced',n_jobs=-1)

In [52]:
print (cross_val_score(model, new_train_data[:, :-1], train_targets, cv=3, scoring='precision_macro').mean())

0.731061807641


In [5]:
new_train_data = np.load('out/new_input.npz')['train']
new_test_data = np.load('out/new_input.npz')['test']

In [9]:
model.fit(new_train_data[:, :-1], train_targets)

LogisticRegression(C=1, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=-1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [10]:
preds = model.predict(new_test_data[:, :-1])
# np.savez('out/preds.npz',preds=preds)

In [11]:
print(accuracy_score(preds, test_targets))

0.744144783534


In [12]:
print(confusion_matrix(test_targets, preds))
print(precision_score(test_targets, preds, average='macro'))

[[5814 1598   43    3    0]
 [ 410 8969  303   20    9]
 [ 123  618 1617   59    4]
 [   1 2091   12  356   94]
 [   4  358    4   14   20]]
0.667062645363
