In [6]:
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import mean_squared_error, precision_score
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [7]:
train_dataset = np.genfromtxt('resources/train.csv', dtype=np.float32, delimiter=',')
train_targets = train_dataset[:,-1]
test_dataset = np.genfromtxt('resources/test.csv', dtype=np.float32, delimiter=',')
test_targets = test_dataset[:,-1]
combined_dataset=np.concatenate((train_dataset[:,:-1], test_dataset[:,:-1]))
train_targets[:5]

array([ 2.,  2.,  1.,  2.,  2.], dtype=float32)

In [8]:
numeric_indices = []
for i in range(combined_dataset.shape[1]):
    n_unique = len(np.unique(combined_dataset[:, i]))
    numeric_indices.append(n_unique > 2)
print (len(numeric_indices))
numeric_indices = np.array(numeric_indices, dtype=np.bool)

122


In [9]:
combined_dataset[:, numeric_indices] = StandardScaler().fit_transform(
                                        combined_dataset[:, numeric_indices]
                                        )

In [16]:
batch_size = 1500
num_feature = 122
num_labels = 5
graph = tf.Graph()
with graph.as_default():

    input_data = tf.placeholder(tf.float32, shape=(None, num_feature))
    clean_data = tf.placeholder(tf.float32, shape=(None, num_feature))
    target = tf.placeholder(tf.float32, shape=(None, 5))
    n_hidden_1 = 200
#     n_hidden_2 = 100
#     n_hidden_3 = 500
    n_input = num_feature

    wh1 = tf.Variable(tf.truncated_normal([n_input, n_hidden_1], dtype=tf.float32))
#     wh2 = tf.Variable(tf.truncated_normal([n_hidden_1, n_hidden_2], dtype=tf.float32))
#     wh3 = tf.Variable(tf.truncated_normal([n_hidden_2, n_hidden_3], dtype=tf.float32))
#     wo = tf.Variable(tf.zeros([n_hidden_1, n_input], dtype=tf.float32))
#     wo.initialized_value = tf.transpose(wh1)
    b1 = tf.Variable(tf.truncated_normal([n_hidden_1], dtype=tf.float32))
#     b2 = tf.Variable(tf.truncated_normal([n_hidden_2], dtype=tf.float32))
#     b3 = tf.Variable(tf.truncated_normal([n_hidden_3], dtype=tf.float32))
    bo = tf.Variable(tf.truncated_normal([n_input], dtype=tf.float32))
    layer_1 = tf.add(tf.matmul(input_data, wh1), b1)
    def compute_logit():
#         layer_2 = tf.nn.relu(tf.add(tf.matmul(layer_1, wh2), b2))
#         layer_3 = tf.nn.sigmoid(tf.add(tf.matmul(layer_2, wh3), b3))
        return tf.matmul(layer_1, tf.transpose(wh1)) + bo 

    
    logits = compute_logit()
    difference = tf.sub(clean_data, logits) 
    loss = tf.sqrt(tf.reduce_mean(tf.square(difference)))# +  0.0001 * (tf.nn.l2_loss(wh1) + tf.nn.l2_loss(wo))
#     loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits,tf_train_dataset))
    optimizer = tf.train.AdamOptimizer(0.001).minimize(loss)
    train_prediction = compute_logit()
    
    
    layer_1_f = tf.add(tf.matmul(clean_data, wh1), b1)
    wy = tf.Variable(tf.truncated_normal([n_hidden_1, num_labels], dtype=tf.float32))
    by = tf.Variable(tf.truncated_normal([num_labels], dtype=tf.float32))
    y_ = tf.matmul(layer_1_f, wy) + by
    loss_ = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(y_, target))
    optimize_ = tf.train.AdamOptimizer(0.0001).minimize(loss_)    

In [20]:
num_steps = 10000
preds = []
randomized_dataset = combined_dataset.copy()
#     np.random.shuffle(randomized_dataset)
new_input=[]
with tf.Session(graph=graph) as session:
    tf.initialize_all_variables().run()
    print ("Initialized")
    for step in range(num_steps):
        offset = (step * batch_size) % (randomized_dataset.shape[0] - batch_size)
        batch_data = randomized_dataset[offset:(offset + batch_size), :]
        noisy_batch_data = batch_data.copy()
        for i, point in enumerate(noisy_batch_data):
            noisy_batch_data[i, :] = point + np.random.normal(0, 1, noisy_batch_data.shape[1])
        feed_dict = {input_data: noisy_batch_data, clean_data: batch_data}
        _, l, predictions = session.run(
          [optimizer, loss, train_prediction], feed_dict=feed_dict)
        if (step % 500 == 0):
            print("Minibatch loss at step", step, ":", l)
#             print "SKLEARN loss", np.sqrt(mean_squared_error(predictions, batch_data))
    new_input=layer_1.eval(feed_dict = {input_data :combined_dataset})

    for step in range(10000):
        c = np.random.choice(train_targets.shape[0], 2000, replace=False)
        batch_data = train_dataset[:,:-1][c]
        batch_targets = train_targets[c]
        batch_targets=LabelBinarizer().fit([1,2,3,4,5]).transform(batch_targets)
        feed_dict = {clean_data:batch_data, target:batch_targets}
        l, _ = session.run([loss_, optimize_], feed_dict=feed_dict)
        if (step % 100 == 0):
            print("Minibatch logloss at step", step, ":", l)
    new_input = layer_1_f.eval(feed_dict={clean_data:combined_dataset})

Initialized
('Minibatch loss at step', 0, ':', 224.05811)
('Minibatch loss at step', 500, ':', 89.803459)
('Minibatch loss at step', 1000, ':', 40.753292)
('Minibatch loss at step', 1500, ':', 16.952778)
('Minibatch loss at step', 2000, ':', 32.826317)
('Minibatch loss at step', 2500, ':', 3.5724339)
('Minibatch loss at step', 3000, ':', 1.6851171)
('Minibatch loss at step', 3500, ':', 0.71821159)
('Minibatch loss at step', 4000, ':', 0.41565123)
('Minibatch loss at step', 4500, ':', 0.38928574)
('Minibatch loss at step', 5000, ':', 0.31946072)
('Minibatch loss at step', 5500, ':', 0.33549848)
('Minibatch loss at step', 6000, ':', 0.36320654)
('Minibatch loss at step', 6500, ':', 0.30072826)
('Minibatch loss at step', 7000, ':', 0.59318727)
('Minibatch loss at step', 7500, ':', 0.30588657)
('Minibatch loss at step', 8000, ':', 0.30118093)
('Minibatch loss at step', 8500, ':', 0.29264712)
('Minibatch loss at step', 9000, ':', 0.30652744)
('Minibatch loss at step', 9500, ':', 0.45049831)

In [43]:
#saving new train & test data 
from collections import Counter
print(train_dataset.shape)
new_train_data=new_input[:train_dataset.shape[0]]
new_train_data=np.c_[new_train_data,train_targets]
new_test_data=new_input[train_dataset.shape[0]:]
new_test_data=np.c_[new_test_data, test_targets]
print(new_train_data.shape, new_test_data.shape)
# np.savez('out/new_input.npz',train=new_train_data, test=new_test_data)

(125973, 123)
(125973, 201) (22544, 201)


In [44]:
model = LogisticRegression(C=1,class_weight='balanced',n_jobs=-1)

In [37]:
print (cross_val_score(model, new_train_data[:, :-1], train_targets, cv=3, scoring='precision_macro').mean())

0.731867870076


In [45]:
new_train_data = np.load('out/new_input.npz')['train']
new_test_data = np.load('out/new_input.npz')['test']

In [46]:
model.fit(new_train_data[:, :-1], train_targets)

LogisticRegression(C=1, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=-1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [47]:
preds = model.predict(new_test_data[:, :-1])
# np.savez('out/preds.npz',preds=preds)

In [50]:
print(accuracy_score(preds, test_targets))

0.742680979418


In [51]:
print(confusion_matrix(test_targets, preds))
print(precision_score(test_targets, preds, average='macro'))

[[5561 1848   45    1    3]
 [ 447 8978  241   19   26]
 [ 153  444 1823    0    1]
 [   2 2142    5  363   42]
 [   1  363    2   16   18]]
0.705047995126
