In [211]:
import pandas as pd
from sklearn.manifold import TSNE
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score
from collections import Counter

In [53]:
train = pd.read_csv('train.csv', header=False)

In [54]:
train.head()

0  1  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8 ...    25  0.17  0.03  0.17.1  \
0  0  0    0    1    0    0    0    0    0    0 ...     1  0.00  0.60    0.88   
1  0  1    0    0    0    0    0    0    0    0 ...    26  0.10  0.05    0.00   
2  0  1    0    0    0    0    0    0    0    0 ...   255  1.00  0.00    0.03   
3  0  1    0    0    0    0    0    0    0    0 ...   255  1.00  0.00    0.00   
4  0  1    0    0    0    0    0    0    0    0 ...    19  0.07  0.07    0.00   

   0.105  0.106  0.107  0.05  0.108  2.2  
0   0.00   0.00   0.00     0   0.00    2  
1   0.00   1.00   1.00     0   0.00    1  
2   0.04   0.03   0.01     0   0.01    2  
3   0.00   0.00   0.00     0   0.00    2  
4   0.00   0.00   0.00     1   1.00    1  

[5 rows x 123 columns]

In [4]:
len(train.iloc[0, :])

123

In [55]:
targets = train.iloc[:, -1]

In [56]:
train.drop(train.columns[[-1]], axis=1, inplace=True)

In [7]:
for i in xrange(1, 6):
    print i, sum(targets == i)

1 45927
2 67342
3 11656
4 995
5 52


In [8]:
test = pd.read_csv('test.csv', header=False)

In [9]:
for i in xrange(1, 6):
    print i, sum(test.iloc[:, -1] == i)

1 7457
2 9711
3 2421
4 2554
5 400


In [10]:
test_targets = test.iloc[:, -1]

In [11]:
test.drop(test.columns[[-1]], axis=1, inplace=True)

In [13]:
model = GradientBoostingClassifier(max_depth=5, random_state=133)

In [14]:
model.fit(train, targets)

GradientBoostingClassifier(init=None, learning_rate=0.1, loss='deviance',
              max_depth=5, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=133, subsample=1.0, verbose=0,
              warm_start=False)

In [31]:
scores = cross_val_score(model, train, targets, n_jobs=-1, cv=10, scoring='precision_macro')
print scores

[ 0.99938996  0.95894341  0.95919094  0.93252162  0.93807932  0.94353841
  0.89733629  0.89727786  0.95549031  0.99935912]


In [32]:
scores.mean()

0.94811272515431999

In [33]:
model.fit(train, targets)

GradientBoostingClassifier(init=None, learning_rate=0.1, loss='deviance',
              max_depth=5, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=133, subsample=1.0, verbose=0,
              warm_start=False)

In [34]:
predictions = model.predict(test)
predictions_proba = model.predict_proba(test)

In [37]:
print accuracy_score(predictions, test_targets)

0.786896154017


In [38]:
print precision_recall_fscore_support(predictions, test_targets)

(array([ 0.82875151,  0.97096077,  0.74969021,  0.11628818,  0.045     ]), array([ 0.96321696,  0.69576446,  0.81171735,  0.98671096,  0.47368421]), array([ 0.89093923,  0.81064351,  0.77947176,  0.20805604,  0.08219178]), array([ 6416, 13552,  2236,   301,    38]))


In [40]:
precision_recall_fscore_support(predictions, test_targets)[0].mean()

0.54213813217179063

###Notes###

- Make separate 1-hot labels for both train and test
- Make the targets into numpy matrix targets.as_matrix()

In [76]:
targets = targets.as_matrix()

In [112]:
r = []
for i in range(1,6):
    r.append(np.arange(len(targets))[targets == i])
def get_batch_indices(class_size):
    n,k = [],[]
    for i in r:
        n.append(len(i))
    for j,i in enumerate(n):
        temp = np.random.choice(i,class_size,replace=False)
        k.extend(r[j][temp])
    return k
   
    

Counter({1: 40, 2: 40, 3: 40, 4: 40, 5: 40})

In [103]:
targets.as_matrix()

AttributeError: 'numpy.ndarray' object has no attribute 'as_matrix'

In [75]:
len(x)

200

In [81]:
r=[]

In [82]:
targets

array([2, 1, 2, ..., 2, 1, 2])

In [84]:
np.arange(len(targets))[targets == 2]

array([     0,      2,      3, ..., 125968, 125969, 125971])

In [85]:
for i in range(1,6):
    r.append(np.arange(len(targets))[targets == i])

In [89]:
r[4]

array([  3172,   5578,   5830,   8674,  11447,  14098,  15187,  15930,
        16726,  16982,  19447,  25325,  25635,  27429,  30532,  36729,
        37269,  40844,  41715,  42395,  42563,  46146,  48749,  53300,
        53888,  54209,  61465,  65085,  66006,  69146,  69475,  69489,
        69941,  72015,  73905,  76814,  77829,  79508,  82251,  84225,
        89256,  91936,  99759, 101584, 102578, 108499, 112931, 113265,
       117340, 118837, 120194, 120497])